### ISSUE TITLE
Authentication error stuck on loading

### ISSUE THREAD

**Issue by mehtahardikr** [crimson1986/trello_like_drag_flutter_app#1]
Authentication error stuck on loading. Please resolved this

**Comment by crimson1986** [comment]
That is because of firebase authentication. You needs to configure your firebase and apply changes in code. Also cloud structure is similar like,

<img width="600" alt="Screen Shot 2020-09-18 at 8 38 49 PM" src="https://user-images.githubusercontent.com/4163452/93614080-4d716b00-f9ef-11ea-845b-74d1823044a2.png">
